name: Build

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - kinetic
          - melodic
          - noetic
        include:
            # Kinetic Kame (May 2016 - May 2021)
          - docker_image: ubuntu:xenial
            ros_distribution: kinetic
            ros_version: 1
            # Melodic Morenia (May 2018 - May 2023)
          - docker_image: ubuntu:bionic
            ros_distribution: melodic
            ros_version: 1
            # Noetic Ninjemys (May 2020 - May 2025)
          - docker_image: ubuntu:focal
            ros_distribution: noetic
            ros_version: 1
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Fetch Repository Name
        run: echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")
        shell: bash
      - name: Setup Directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src
      - name: Setup ROS Environment
        uses: ros-tooling/setup-ros@0.0.25
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Update rosdep
        run: rosdep update
      - name: install catkin_ws dependencies
        run: "source /opt/ros/$DISTRO/setup.bash && cd ros_ws/ && rosdep install --from-paths src --ignore-src -r -y"
        env:
          DISTRO: ${{ matrix.ros_distribution }}
        shell: bash
      - name: Build and Test
        run: "source /opt/ros/$DISTRO/setup.bash && cd ros_ws/ && catkin_make run_tests roslint_$REPOSITORY_NAME"
        env:
          DISTRO: ${{ matrix.ros_distribution }}
        shell: bash
